MINI_Cab/MINI_Cab/Areas/User/Controllers/User_DashboardController.cs
using Elmah;
using MINI_Cab.App_Code;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MINI_Cab.Models;
using System.IO;
//using MINI_Cab.Areas.User.Models;

namespace MINI_Cab.Areas.User.Controllers
{
    public class User_DashboardController : Controller
    {
        Common_Function db = new Common_Function();
        // GET: User/User_Dashboard
        #region GET_Method
        public ActionResult Dashboard()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            DataSet ds = db.LastFiveJobs(Convert.ToInt32(Session["UserId"]));
            return View(ds);
        }
        public ActionResult Book_a_job()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session["UserId"] = null;
            Session["UserId"] = "";
            Session["UserImg"] = "";
            Session["UserImg"] = null;
            Session["UserID"] = "";
            Session["UserName"] = "";
            Session["UserID"] = null;
            Session["UserName"] = null;

            Session.Clear();

            return RedirectToAction("Login", "Login", new { area = "" });
        }
        public ActionResult Track_a_cab()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            return View();
        }
        public ActionResult User_profile()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            return View();
        }
        #endregion

        #region POST Method

        [HttpPost]
        public ActionResult getUserProfile()
        {
            DataSet ds = db.GetUserData(Convert.ToInt32(Session["UserId"]));
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> parentRow = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow;
            try
            {
                if (Session["UserId"] == null)
                {
                    return RedirectToAction("Login", "Login", new { area = "" });
                }
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    childRow = new Dictionary<string, object>();
                    foreach (DataColumn col in ds.Tables[0].Columns)
                    {
                        childRow.Add(col.ColumnName, row[col]);
                    }
                    parentRow.Add(childRow);
                }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return Json(new { data = jsSerializer.Serialize(parentRow) });
        }

        [HttpPost]
        public ActionResult UpdateUserProfile(UserManagement u)
        {
            string msg = "";
            try
            {
                u.usm_id = Convert.ToInt32(Session["UserId"]);
                u.usm_updatedby = Convert.ToInt32(Session["UserId"]);
                u.usm_createdby = Session["UserId"].ToString();
                db.AddUserMaster(u);
                msg = "success";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { status = msg });
        }

        [HttpPost]
        public ActionResult UpdateChangePassword(string OldPasword, string NewPassword)
        {
            string result = "";
            try
            {
                if (Session["UserId"] == null)
                {
                    return RedirectToAction("Login", "Login", new { area = "" });
                }
                result = db.ChangePassword(OldPasword, NewPassword, Session["UserId"].ToString());
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { data = result });
        }
      
        [HttpPost]
        public ActionResult Track_a_job_data()
        {
            int result = 0;
            DataSet ds = db.track_a_cab(Convert.ToInt32(Session["UserId"]));
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> parentRow = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow;
            try
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    childRow = new Dictionary<string, object>();
                    foreach (DataColumn col in ds.Tables[0].Columns)
                    {
                        childRow.Add(col.ColumnName, row[col]);
                    }
                    parentRow.Add(childRow);
                }
                if (ds.Tables[0].Rows.Count == 0)
                {
                    result = 1;
                }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { data = jsSerializer.Serialize(parentRow), result = result });
        }

        [HttpPost]
        public ActionResult UploadProfile(HttpPostedFileBase file)
        {
            string status = "";
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        file = files[i];
                        string fname;
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }

                        string FileExt = Path.GetExtension(file.FileName);
                        string F_Fullname = "_" + Session["UserId"].ToString() + FileExt;
                        fname = Path.Combine(Server.MapPath("~/UserPicture/"), F_Fullname);
                        string OldProfile = Session["UserImg"].ToString();
                        string OldFullPath = Server.MapPath("~/UserPicture/" + OldProfile);
                        if ((System.IO.File.Exists(OldFullPath)))
                        {
                            System.IO.File.Delete(OldFullPath);
                        }

                        file.SaveAs(fname);

                        db.UpdateProfile(Session["UserId"].ToString(), F_Fullname);
                        Session["UserImg"] = F_Fullname;
                        status = "success";
                    }
                }
                catch (Exception ex)
                {
                    ErrorSignal.FromCurrentContext().Raise(ex);
                }
            }
            return Json(new { status = status });
        }

        #endregion  
    }
}

MINI_Cab/MINI_Cab/Areas/User/Views/User_Dashboard/Dashboard.cshtml
@using System.Data
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}
<style>
    thead {
        display: none;
    }

    .table-box table tr td {
        text-align: left;
    }

    body {
        counter-reset: Serial;
    }

    .black-backhround table {
        border-collapse: separate;
    }

   .black-backhround tr td:first-child:before {
        counter-increment: Serial; 
        content: "" counter(Serial);
    }
</style>

<div class="dashboard-right">
    <div class="dashboard-icon">
        <ul>
            <li><a href="@Url.Action("Book_a_Job","User_Dashboard",new { area="User"})"><i class="fa fa-book"></i><p>book cab</p></a></li>
            <li><a href="@Url.Action("Track_a_cab","User_Dashboard",new { area="User"})"><i class="fa fa-calendar-check-o"></i><p>track a cab</p></a></li>
        </ul>
    </div>

    <div class="table-box">
        <h6>last 5 Journey</h6>
        <table>
            <tr>
                <td style="text-align:center;width:200px"><a href="#">Job Id</a></td>
                <td style="width:400px;text-align:left"><a href="#">From Job</a></td>
                <td style="width:600px;text-align:left"><a href="#">To Job </a></td>
            </tr>
        </table>
        @if (Model.Tables[0].Rows.Count == 0)
        {
            <div style="text-align: center;"><h3 style="padding:9px;">No Job Found !</h3></div>
        }
        @foreach (DataRow row in Model.Tables[0].Rows)
        {
            <table class="black-backhround">
                <tr>
                    <td style="text-align:center;width:200px"><a href="#"></a></td>
                    <td style="width:400px;text-align:left"><a href="#">@row["from_job_postcode"]</a>  <a>@row["from_job_address"]</a>   <a>@row["from_job_street"]</a></td>
                    <td style="width:600px;text-align:left"><a href="#">@row["tojob_address"]</a></td>
                </tr>
            </table>
        }
    </div>
</div>

MINI_Cab/MINI_Cab/Areas/User/Views/User_Dashboard/Track_a_cab.cshtml
@using System.Data
@{
    ViewBag.Title = "Track_a_job";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}
<style>
    #map {
        width: 100%;
        height: 100%;
    }

    #map_damy {
        width: 50%;
        height: 100%;
        margin-top: 11%;
        margin-left: 20%;
    }

    #gmimap5 {
        display: none !important;
    }
   
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6NJR2j3dlZdZNh_n7FZDghYULahe-eKM"></script>
<script>

    var lat_val = '';
    var lng_val = '';
    var cab_title = '';
    var User_latitude = '';
    var User_longitude = '';
    var markers = [{ "lat": 51.509865, "lng": -0.118092 }, { "lat": 51.509865, "lng": -0.118092 }];
    var CounterA = 0;
    $(document).ready(function () {
        $(function () {
            mapLocation();
            var UserId = '@Session["UserID"]';
            var socket = io.connect("http://localhost:8083");
            socket.emit('UserId', UserId);
            socket.on('showrows', function (dataJourney) {
               // RemovePoint();
                markers = [];
                console.log(dataJourney.recordsets[0]);
                track_a_job(dataJourney.recordsets[0]);
            });
            
        });
    });

    window.onload = function () {
        setInterval(function () {
            //RemovePoint();
            document.getElementById('routebtn').click();
        }, 2000);
    }
    //function RemovePoint() {
    //    var images = document.getElementsByTagName('img');

    //    for (var i = 0; i < images.length; i++) {
    //        if ((images[i].src).includes('data:image/svg')) {
    //            $('img[src="' + (images[i].src) + '"]').css("display", "none");
    //        }
    //    }
    //}
    function track_a_job(jsondata) {
        $('#map_damy').empty();
        if (jsondata.length > 0) {
            if (jsondata[0].status == '1') {
                $('#map_damy').hide();
                var driverLocation = { "lat": jsondata[0].driver_let, "lng": jsondata[0].driver_lon }
                markers.push(driverLocation);
                cab_title = (jsondata[0].tariff_name);
                var geocoder = new google.maps.Geocoder();

                if (CounterA == 0) {
                    geocoder.geocode({ 'address': jsondata[0].from_job_address }, function (results, status) {

                        if (status == google.maps.GeocoderStatus.OK) {
                            User_latitude = results[0].geometry.location.lat();
                            User_longitude = results[0].geometry.location.lng();

                        }
                    });
                }
                var driverLocation = { "lat": User_latitude, "lng": User_longitude }
                markers.push(driverLocation);

            } else { $('#map').hide(); $('#map_damy').append(' <div style="text-align: center;"><h4 style="padding:9px;border: 1px solid gray;">Please Wait..Finding Nearest Driver !</h4></div>'); }
        } else { $('#map').hide(); $('#map_damy').append(' <div style="text-align: center;"><h4 style="padding:9px;border: 1px solid gray;">No Cab Found !</h4></div>'); }
    }

    function mapLocation() {
        var directionsDisplay;
        var directionsService = new google.maps.DirectionsService();
        var map;

        function initialize() {
            directionsDisplay = new google.maps.DirectionsRenderer();
            var chicago = new google.maps.LatLng(markers[0].lat, markers[0].lng);
            var mapOptions = {
                zoom: 7,
                center: chicago
            };
            map = new google.maps.Map(document.getElementById('map'), mapOptions);
            directionsDisplay.setMap(map);
            google.maps.event.addDomListener(document.getElementById('routebtn'), 'click', calcRoute);

        }
        var marker = null;
        function calcRoute() {
            if (marker) {
                marker.setMap(null);
            }
            var start = new google.maps.LatLng(markers[0].lat, markers[0].lng);
            var end = new google.maps.LatLng(markers[1].lat, markers[1].lng);
            var request = {
                origin: start,
                destination: end,
                travelMode: google.maps.TravelMode.DRIVING
            };
            marker = new google.maps.Marker({
                position: end,
                map: map//,
               // icon: '../../Themes/images/pesanger.png'
            });
            marker = new google.maps.Marker({
                position: start,
                map: map///,
                //icon: '../../Themes/images/texti.png'
            });
            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                    directionsDisplay.setMap(map);
                }

            });
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    }

</script>
<div class="dashboard-right">
    <div class="dashboard-icon">
        <ul>
            <li><a href="@Url.Action("Book_a_Job","User_Dashboard",new { area="User"})"><i class="fa fa-book"></i><p>book cab</p></a></li>
            <li><a href="@Url.Action("Track_a_cab","User_Dashboard",new { area="User"})"><i class="fa fa-calendar-check-o"></i><p>track a cab</p></a></li>
        </ul>
    </div>
    <div class="table-box">
        <h6>track a cab</h6>
        <div class="page-from-bg track-page-map">
            <input type="button" id="routebtn" value="route" style="display:none;" />
            <div id="map"></div>
            <div id="map_damy"></div>
        </div>
        <div class="table-box">
        </div>
    </div>
</div>

MINI_Cab/MINI_Cab/Areas/User/Views/User_Dashboard/User_profile.cshtml
@{
    ViewBag.Title = "User_profile";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}
<script>
    $(document).ready(function () {
        if (!Number.prototype.toLowerCase) {
            Number.prototype.toLowerCase = function () {
                return this.toString();
            }
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            url: '@Url.Action("getUserProfile", "User_Dashboard", new { area = "User" })',
            success: function (data) {
                var dataJSON = JSON.parse(data.data);
                $('#txt_firstname').val(dataJSON[0].usm_fname);
                $('#txt_lastname').val(dataJSON[0].usm_lname);
                $('#txt_email').val(dataJSON[0].usm_email);
                $('#txt_mobile').val(dataJSON[0].usm_phone);
                $('#txt_address').val(dataJSON[0].usm_address);
                $('#txt_city').val(dataJSON[0].usm_city);
                $('#txt_state').val(dataJSON[0].usm_state);
                $('#txt_country').val(dataJSON[0].usm_country);
            }
        });
    });
    function update_Profile() {
        var FirstName_txt = (CheckValueNullOrNOT($('#txt_firstname').val()));
        if (!FirstName_txt) { alert('Enter First name'); return; }

        var LastName_txt = (CheckValueNullOrNOT($('#txt_lastname').val()));
        if (!LastName_txt) { alert('Enter Last name'); return; }

        var Email_txt = (CheckEmail($('#txt_email').val()));
        if (!Email_txt) {
            alert('Please Enter Valid Email'); return;
        }

        var Mobile_txt = (MobileValidation($('#txt_mobile').val()));
        if (!Mobile_txt) { alert('Enter Valid Mobile'); return; }

        var Address_txt = (CheckValueNullOrNOT($('#txt_address').val()));
        if (!Address_txt) { alert('Enter Address'); return; }

        var Country_txt = (CheckValueNullOrNOT($('#txt_country').val()));
        if (!Country_txt) { alert('Enter Country'); return; }

        var State_txt = (CheckValueNullOrNOT($('#txt_state').val()));
        if (!State_txt) { alert('Enter State'); return; }

        var City_txt = (CheckValueNullOrNOT($('#txt_city').val()));
        if (!City_txt) { alert('Enter City'); return; }

        if (FirstName_txt && LastName_txt && Email_txt && Mobile_txt && Address_txt && Country_txt && State_txt && City_txt) {
            $.showLoading({ name: 'circle-turn' });
            var data = {
                usm_fname: $('#txt_firstname').val(),
                usm_lname: $('#txt_lastname').val(),
                usm_email: $('#txt_email').val(),
                usm_phone: $('#txt_mobile').val(),
                usm_address: $('#txt_address').val(),
                usm_city: $('#txt_city').val(),
                usm_state: $('#txt_state').val(),
                usm_userrole: '2',
                usm_country: $('#txt_country').val(),
            }
            $.ajax({
                type: "POST",
                dataType: "json",
                url: '@Url.Action("UpdateUserProfile", "User_Dashboard", new { area = "User" })',
                data: data,
                success: function (data) {
                    $.hideLoading({ name: 'circle-turn' });
                    if (data.status == 'success')
                    { alert('Profile Update Successfully.') }
                }
            });
        }
    }
</script>

<div class="dashboard-right">
    <div class="dashboard-icon">
        <ul>
            <li><a href="@Url.Action("Book_a_Job","User_Dashboard",new { area="User"})"><i class="fa fa-book"></i><p>book cab</p></a></li>
            <li><a href="@Url.Action("Track_a_cab","User_Dashboard",new { area="User"})"><i class="fa fa-calendar-check-o"></i><p>track a cab</p></a></li>
        </ul>
    </div>
    <div class="table-box">
        <h6>Profile info</h6>
        <div class="page-from-bg">
            <div class="book-form">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12 from-box-width">
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                First Name:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="First Name *" type="text" id="txt_firstname" maxlength="25">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                Email:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="Email *" type="text" id="txt_email" maxlength="50">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                Mobile:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="Mobile *" type="number" id="txt_mobile" onKeyDown="if(this.value.length==15 && event.keyCode!=8) return false;">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                State:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="State *" type="text" id="txt_state" maxlength="20">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 from-box-width">
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                Last Name:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="Last Name *" type="text" id="txt_lastname" maxlength="25">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                Address:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="Address *" type="text" id="txt_address" maxlength="200">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                City:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="City *" type="text" id="txt_city" maxlength="25">
                            </div>
                        </div>
                        <div class="control-group">
                            <label for="selsear" class="control-label">
                                Country:<span style="color: red">*</span>
                            </label>
                            <div class="from-box">
                                <input placeholder="Country : *" type="text" id="txt_country" maxlength="25">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-btn">
                    <ul>
                        <li><a href="#" onclick="update_Profile();">update</a></li>
                        <li><a href="@Url.Action("Dashboard","User_Dashboard",new { area="User"})">Cancel</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>