MINI_Cab/MINI_Cab/Areas/Admin/Controllers/AdminPannelController.cs
using MINI_Cab.App_Code;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MINI_Cab.Areas.Admin.Models;
using System.Globalization;
using System.Net.Http;
using Newtonsoft.Json;
using System.Threading.Tasks;
using Elmah;

namespace MINI_Cab.Areas.Admin.Controllers
{
    public class AdminPannelController : Controller
    {
        Common_Function db = new Common_Function();

        string motdata = "";
        // GET: Admin/AdminPannel
        public ActionResult AdminPanel()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            return View();
        }
        [HttpPost]
        public ActionResult get_tarrifs()
        {
            DataSet ds_tariff = new DataSet();
            DataSet ds_driver = new DataSet();
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> parentRow_tarif = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow_tarif;
            List<Dictionary<string, object>> parentRow_driver = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow_driver;
            try
            {
                ds_tariff = db.get_tariffs(0);
                foreach (DataRow row in ds_tariff.Tables[0].Rows)
                {
                    childRow_tarif = new Dictionary<string, object>();
                    foreach (DataColumn col in ds_tariff.Tables[0].Columns)
                    {
                        childRow_tarif.Add(col.ColumnName, row[col]);
                    }
                    parentRow_tarif.Add(childRow_tarif);
                }
                ds_driver = db.get_drivers(0);
                foreach (DataRow row in ds_driver.Tables[0].Rows)
                {
                    childRow_driver = new Dictionary<string, object>();
                    foreach (DataColumn col in ds_driver.Tables[0].Columns)
                    {
                        childRow_driver.Add(col.ColumnName, row[col]);
                    }
                    parentRow_driver.Add(childRow_driver);
                }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return Json(new { data_tarif = jsSerializer.Serialize(parentRow_tarif), data_driver = jsSerializer.Serialize(parentRow_driver) });
        }

        [HttpPost]
        public ActionResult Get_Payment(int Pay_Id)
        {
            DataSet ds_Payment = new DataSet();
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> parentRow_Payment = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow_Payment;
            try
            {
                ds_Payment = db.GetPayment(Pay_Id);
                foreach (DataRow row in ds_Payment.Tables[0].Rows)
                {
                    childRow_Payment = new Dictionary<string, object>();
                    foreach (DataColumn col in ds_Payment.Tables[0].Columns)
                    {
                        childRow_Payment.Add(col.ColumnName, row[col]);
                    }
                    parentRow_Payment.Add(childRow_Payment);
                }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return Json(new { data_Payment = jsSerializer.Serialize(parentRow_Payment) });
        }

        [HttpPost]
        public ActionResult getDriverTarrifwise(int jobid)
        {
            DataSet ds_tariff = new DataSet();
            DataSet ds_driver = new DataSet();
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            List<Dictionary<string, object>> parentRow_tarif = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow_tarif;
            List<Dictionary<string, object>> parentRow_driver = new List<Dictionary<string, object>>();
            Dictionary<string, object> childRow_driver;
            try
            {
                ds_tariff = db.get_tariffs(0);
                foreach (DataRow row in ds_tariff.Tables[0].Rows)
                {
                    childRow_tarif = new Dictionary<string, object>();
                    foreach (DataColumn col in ds_tariff.Tables[0].Columns)
                    {
                        childRow_tarif.Add(col.ColumnName, row[col]);
                    }
                    parentRow_tarif.Add(childRow_tarif);
                }
                ds_driver = db.getDriverTarrifwise(jobid);
                foreach (DataRow row in ds_driver.Tables[0].Rows)
                {
                    childRow_driver = new Dictionary<string, object>();
                    foreach (DataColumn col in ds_driver.Tables[0].Columns)
                    {
                        childRow_driver.Add(col.ColumnName, row[col]);
                    }
                    parentRow_driver.Add(childRow_driver);
                }
            }
            catch (Exception ex)
            {

                ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return Json(new { data_tarif = jsSerializer.Serialize(parentRow_tarif), data_driver = jsSerializer.Serialize(parentRow_driver) });
        }
        [HttpPost]
        public ActionResult ADD_a_tariffs(tariff_model t)
        {
            string msg = "";
            try
            {
                t.createdate = DateTime.Now;
                t.created_by = 1;
                t.updateddate = DateTime.Now;
                t.updated_by = 1;
                string result = db.ADD_tariffs(t);
                if (result == "success")
                { msg = "success"; }
                else { msg = "fail"; }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

        [HttpPost]
        public ActionResult ADD_Payment(Payment P)
        {
            string msg = "";
            try
            {
                P.Pay_CreatedDate = DateTime.Now;
                P.Pay_CreatedBy = Convert.ToInt32(Session["UserId"]);
                P.Pay_UpdatedDate = DateTime.Now;
                P.Pay_UpdatedBy = Convert.ToInt32(Session["UserId"]);
                db.ADD_PaymentMethod(P);
                msg = "success";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

        [HttpPost]
        public ActionResult ADD_a_drivers(driver_models d)
        {
            string msg = "";
            try
            {
                DateTime driver_insurance = DateTime.Parse(d.driver_insurance.ToString(), CultureInfo.CreateSpecificCulture("fr-FR"));
                //DateTime vehi_pco_expiry1 = DateTime.Parse(d.driver_phv_expiry, CultureInfo.CreateSpecificCulture("fr-FR"));
                //DateTime driver_insurance1 = DateTime.Parse(d.driver_insurance, CultureInfo.CreateSpecificCulture("fr-FR"));
                //////d.driver_pco_expiry = driver_pco_expiry1.ToString();
                //////d.driver_phv_expiry = vehi_pco_expiry1.ToString();
                //d.driver_insurance = driver_insurance1.ToString();
                d.driver_insurance = driver_insurance.ToString("MM/dd/yyyy");
                if (d.driver_insurance == null)
                {
                    d.driver_insurance = DateTime.MaxValue.ToString("MM/dd/yyyy");
                }

                string result = db.ADD_drivers(d);
                if (result == "success")
                { msg = "success"; }
                else { msg = "fail"; }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

        [HttpPost]
        public ActionResult delete_tariff(int tarif_id)
        {
            string msg = "";
            try
            {
                db.delete_tarif(tarif_id);
                msg = "success";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

        [HttpPost]
        public ActionResult delete_driver(int driver_id)
        {
            string msg = "";
            try
            {
                db.delete_driver(driver_id);
                msg = "success";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

        [HttpPost]
        public ActionResult DeletePayment(int Payment_Id)
        {
            string msg = "";
            try
            {
                db.DeletePayment(Payment_Id);
                msg = "success";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

        [HttpPost]
        public ActionResult OverRide(string or_Id, string reason, DateTime date, int driverNo)
        {
            string msg = "";
            try
            {
                db.ADD_OverRide(or_Id, reason, date, driverNo, Convert.ToInt32(Session["UserId"]));
                msg = "success";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }

MINI_Cab/MINI_Cab/Areas/Admin/Controllers/bookingController.cs
using Elmah;
using getAddress.Sdk;
using getAddress.Sdk.Api.Requests;
using getAddress.Sdk.Api.Responses;
using MINI_Cab.App_Code;
using MINI_Cab.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MINI_Cab.Areas.Admin.Controllers
{
    public class bookingController : Controller
    {
        // GET: Admin/booking
        Common_Function db = new Common_Function();
        public ActionResult booking_form()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Login", new { area = "" });
            }
            return View();
        }
        [HttpPost]
        public ActionResult book_a_job(fromjob_booking datafrom_job, string datato_job)
        {
            string msg = "";
            try
            {
                datafrom_job.user_id =Convert.ToInt32(Session["UserId"]);
                int from_jobid = db.Add_from_job(datafrom_job);

                string[] to_job = datato_job.TrimEnd('+').Split('+');
                foreach (var job in to_job)
                {
                    string[] single_job = job.Split('$');
                    db.Add_to_job(single_job[2], single_job[1], single_job[0], from_jobid);
                }
                msg = "sucess";
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
            }
            return Json(new { msg = msg });
        }
        [HttpPost]
        public async Task<ActionResult> get_postcode_to_address(string postcode)
        {
            var apiKey = new ApiKey(ConfigurationManager.AppSettings["AddressCheckAPIKey"]);
            JsonResponse resp = new JsonResponse();
            using (var api = new GetAddesssApi(apiKey))
            {
                var result = await api.Address.Get(new GetAddressRequest(postcode));

                if (result.IsSuccess)
                {
                    var successfulResult = (GetAddressResponse.Success)result;
                    //  int count = 0;
                    List<AddressDataWeb> addresses = new List<AddressDataWeb>();
                    foreach (var address in successfulResult.Addresses)
                    {
                        string newaddress = null;

                        if (address.Line1 != null && address.Line1 != " " && address.Line1 != "")
                        {
                            newaddress = address.Line1;
                        }
                        if (address.Line2 != null && address.Line2 != " " && address.Line2 != "")
                        {
                            newaddress = newaddress + ", " + address.Line2;
                        }
                        if (address.Line3 != null && address.Line3 != " " && address.Line3 != "")
                        {
                            newaddress = newaddress + ", " + address.Line3;
                        }
                        if (address.Line4 != null && address.Line4 != " " && address.Line4 != "")
                        {
                            newaddress = newaddress + ", " + address.Line4;
                        }
                        if (address.TownOrCity != null && address.TownOrCity != " " && address.TownOrCity != "")
                        {
                            newaddress = newaddress + ", " + address.TownOrCity;
                        }
                        if (address.Locality != null && address.Locality != " " && address.Locality != "")
                        {
                            newaddress = newaddress + ", " + address.Locality;
                        }
                        if (address.County != null && address.County != " " && address.County != "")
                        {
                            newaddress = newaddress + ", " + address.County;
                        }

                        addresses.Add(new AddressDataWeb { AddressId = newaddress, AddressString = newaddress });
                    }
                    resp.data = addresses;
                    resp.status = true;
                    resp.message = "Postcode is valid";
                    return Json(resp);
                }
                else
                {
                    resp.data = null;
                    resp.status = false;
                    resp.message = "Please enter valid postcode";
                    return Json(resp);
                }
            }

        }
       
    }
}
public class JsonResponse
{
    public JsonResponse()
    {
        status = false;
        message = "";
        id = 0;
        data = new object();
    }
    public Boolean status { get; set; }
    public string message { get; set; }
    public int id { get; set; }
    public object data { get; set; }
    public int HttpStatusCode { get; set; }
}

MINI_Cab/MINI_Cab/Areas/Admin/Views/Shared/_AdminPanel.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
    <link rel="shortcut icon" href="~/Themes/images/favicon.ico" />

    <link href="~/Themes/css/loading.min.css" rel="stylesheet" />
    <link href="~/Themes/css/CommonClass.css" rel="stylesheet" />
    <link href="~/Themes/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Themes/css/style.css" rel="stylesheet">
    <link href="~/Themes/css/responsive.css" rel="stylesheet">
    <link href="~/Themes/css/fonts.css" rel="stylesheet">
    <link href="~/Themes/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Themes/css/menu-style.css" rel="stylesheet" />
    <link href="~/Themes/css/kendo.common-material.min.css" rel="stylesheet" />
    <link href="~/Themes/css/kendo.material.min.css" rel="stylesheet" />
    <link href="~/Themes/css/CommonClass.css" rel="stylesheet" />
    <link href="~/Themes/css/animate.css" rel="stylesheet" />
    <link href="~/Themes/css/qry_new.css" rel="stylesheet" />
    <link href="~/Themes/css/jquery-clockpicker.css" rel="stylesheet" />
    <link href="~/Themes/css/CustomeBord.css" rel="stylesheet" />
    <link href="~/Themes/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/Themes/css/main.css" rel="stylesheet">
    <link href="~/Themes/css/jquery-ui-range-slider.css" rel="stylesheet">
    @*<link href="~/Themes/css/color1.css" rel="stylesheet" />*@
    <link href="~/Themes/css/colorPicker.css" rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
    <script src="~/Themes/js/jquery.colorPicker.js"></script>
    <script src="~/Themes/js/color1.js"></script>
    <script src="~/Themes/js/jquery-clockpicker.js"></script>
    <script src="~/Themes/js/kendo.all.min.js"></script>
    <script src="~/Themes/js/jquery.loading.min.js"></script>
    <script src="~/Themes/CommonFunction/CommonFunction.js"></script>
    <script src="~/Themes/js/bootstrap.min.js"></script>
    <script src="~/Themes/js/underscore-min.js"></script>
    <script src="~/Themes/js/jquery_003.js"></script>
    <script src="~/Themes/js/jquery_002.js"></script>
    <script src="~/Themes/js/jquery.js"></script>
    <script src="~/Themes/js/Menu.js"></script>
    <script>
        $(document).ready(function () {
            if (!Number.prototype.toLowerCase) {
                Number.prototype.toLowerCase = function () {
                    return this.toString();
                }
            }
            var UserName = '@Session["UserName"]';
            var date = new Date();
            var n = date.toDateString();
            var time = date.toLocaleTimeString();
            $('#datetime_lable').text(n + ' ' + time);
            $('#login_Username').text('User Name : ' + UserName);
            setInterval(function () {
                var date = new Date();
                var n = date.toDateString();
                var time = date.toLocaleTimeString();
                $('#datetime_lable').text(n + ' ' + time);
            }, 100);
        });
    </script>
</head>
<body>
    <div class="wrapper">
        <nav id="sidebar" class="left-sidebar">
            <div class="dashboard-logo">
                <a href="#"><img src="~/Themes/images/pinpoint-7.png" alt="user"></a>
            </div>
            <div class="mm-page">
                <form method="post" action="./ListZoneMaster.aspx" id="frm_Lease">
                    <div class="main">
                        <div class="middle">
                            <div id="left">
                                <ul id="nav">
                                    <li>
                                        <a class="link" href="#">
                                            <span id="Left1_rpt_Menu_l_GroupName_0">Master Group</span>
                                        </a>
                                        <ul>
                                            <li><a class="link" href="@Url.Action("Admin_Dashboard", "Admin_Dashboard", new { area = "Admin" })"><img src="~/Themes/images/branch-master-3.png" alt="branch-master">Dashboard</a></li>
                                            <li><a class="link" href="@Url.Action("AdminPanel", "AdminPannel", new { area = "Admin" })"><img src="~/Themes/images/company-icon-2.png" alt="Company-master">Admin Panel</a></li>
                                            <li><a class="link" href="@Url.Action("OperatorConsole", "OperatorConsole", new { area = "Admin" })"><img src="~/Themes/images/branch-master-3.png" alt="branch-master">Operator Console</a></li>
                                            <li><a class="link" href="@Url.Action("booking_form", "booking", new { area = "Admin" })"><img src="~/Themes/images/branch-master-3.png" alt="branch-master">Book Job</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </nav>

        <div id="content" class="pd-rgt">

            <div class="logout-top">
                <div class="date-time">
                    <span id="datetime_lable"></span>
                    <span id="login_Username"></span>
                </div>
                <a href="@Url.Action("Logout","OperatorConsole",new { area="Admin"})">logout <i class="fa fa-sign-out"></i></a>
                <nav class="navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                            <i class="glyphicon glyphicon-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>
                    </div>
                </nav>
            </div>
            <div class="clearfix"></div>
            @RenderBody()
        </div>
    </div>
</body>
</html>